# Generated by Django 3.0.3 on 2020-03-21 04:52

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BugType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1)),
                ('departmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.Department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FunctionalArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Severity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('release', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('name', models.CharField(max_length=200, unique=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.FunctionalArea')),
            ],
            options={
                'unique_together': {('name', 'version'), ('name', 'release', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachmentID', models.CharField(max_length=1000)),
                ('summary', models.CharField(max_length=500)),
                ('suggestedFix', models.CharField(max_length=500)),
                ('issueDate', models.DateTimeField(default=datetime.datetime(2020, 3, 21, 4, 52, 7, 160168, tzinfo=utc))),
                ('isAssignedToGroup', models.BooleanField()),
                ('comments', models.CharField(max_length=500)),
                ('resolveByDate', models.DateTimeField()),
                ('testByDate', models.DateTimeField()),
                ('treatedAsDeferred', models.BooleanField()),
                ('reproducible', models.BooleanField()),
                ('assignedToID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignedToID', to='issues.Employee')),
                ('bugtypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.BugType')),
                ('functionalAreaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.FunctionalArea')),
                ('priorityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.Priority')),
                ('programID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.Program')),
                ('reportedByID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_reportedByID', to='issues.Employee')),
                ('resolutionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.Resolution')),
                ('severityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.Severity')),
                ('statusID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.Status')),
                ('testedByID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_testedByID', to='issues.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('members', models.ManyToManyField(to='issues.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=500)),
                ('typeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.AttachmentType')),
            ],
        ),
    ]
