# Generated by Django 3.0.3 on 2020-04-29 01:50

from django.db import migrations
from django.contrib.auth.models import User
from issues.models import Employee


def create_superuser(apps, schema_editor):
    user = User.objects.create_superuser(
        username='root', password='root', email='root@gmail.com')

    employee = Employee(user=user, level=3,
                        first_name="root", last_name="root")
    employee.save()
    

people = [
    {
        'username': 'timmy!',
        'password': 'timmy',
        'first_name': 'Timmy',
        'last_name': '',
        'level': 3
    },
    {
        'username': 'jorge',
        'password': 'jorge',
        'first_name': 'Jorge',
        'last_name': '',
        'level': 2
    },
    {
        'username': 'smith',
        'password': 'jorge',
        'first_name': 'Hannah',
        'last_name': '',
        'level': 2
    },
    {
        'username': 'johanng',
        'password': 'johanng',
        'first_name': 'Johann',
        'last_name': 'Gomblepuddy',
        'level': 1
    },
    {
        'username': 'leroisoleil',
        'password': 'leroisoleil',
        'first_name': 'Louis',
        'last_name': 'XIV',
        'last_name': '',
        'level': 2
    },
    {
        'username': 'jonesbrenda',
        'password': 'jonesbrenda',
        'first_name': 'Brenda',
        'last_name': '',
        'level': 1
    },
    {
        'username': 'smithp',
        'password': 'smithp',
        'first_name': 'Prakish',
        'last_name': '',
        'level': 2
    },
    {
        'username': 'liam',
        'password': 'liam',
        'first_name': 'Liam',
        'last_name': 'Nguyen',
        'level': 3
    },
    {
        'username': 'marco',
        'password': 'marco',
        'first_name': 'Marco',
        'last_name': 'Curci',
        'level': 2
    },
    {
        'username': 'dillion',
        'password': 'dillion',
        'first_name': 'Dillion',
        'last_name': 'Brown',
        'level': 3
    },

]


def create_other_users(apps, schema_editor):
    for person in people:
        user = User.objects.create_user(
            username=person['username'], password=person['password'])
        employee = Employee(
            user=user, first_name=person['first_name'], 
            last_name=person['last_name'], level=person['level'])
        employee.save()
        

def create_all(apps, schema_editor):
    create_superuser(apps, schema_editor)
    create_other_users(apps, schema_editor)

class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [migrations.RunPython(
        create_all)]

