# Generated by Django 3.0.3 on 2020-03-21 05:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='functionalarea',
            old_name='area',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='issue',
            name='issueDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
