# Generated by Django 3.0.3 on 2020-03-21 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20200321_0516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='assignedToID',
            new_name='assignedTo',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='attachmentID',
            new_name='attachment',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='bugtypeID',
            new_name='bugtype',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='functionalAreaID',
            new_name='functionalArea',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='priorityID',
            new_name='priority',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='programID',
            new_name='program',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='reportedByID',
            new_name='reportedBy',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='resolutionID',
            new_name='resolution',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='severityID',
            new_name='severity',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='statusID',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='testedByID',
            new_name='testedBy',
        ),
    ]
