# Generated by Django 3.0.3 on 2020-03-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_auto_20200321_0517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='area',
        ),
        migrations.AddField(
            model_name='program',
            name='area',
            field=models.ManyToManyField(to='issues.FunctionalArea'),
        ),
    ]
