# Generated by Django 3.0.3 on 2020-03-21 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_auto_20200321_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.ForeignKey(default='OPEN', on_delete=django.db.models.deletion.CASCADE, to='issues.Status'),
        ),
    ]
