# Generated by Django 3.0.3 on 2020-03-22 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0009_auto_20200322_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='level',
            field=models.IntegerField(choices=[(1, '1'), (2, '2')], default=1),
        ),
    ]
