# Generated by Django 3.0.3 on 2020-04-22 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0011_auto_20200422_0620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='area',
            new_name='areas',
        ),
    ]
