# Generated by Django 3.0.3 on 2020-04-22 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0016_auto_20200422_0901'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='program',
            unique_together=set(),
        ),
    ]
