# Generated by Django 3.0.3 on 2020-04-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0018_auto_20200422_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='name',
            field=models.CharField(default='random', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='issue_images/'),
        ),
    ]
