# Generated by Django 3.0.3 on 2020-04-29 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0019_auto_20200428_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='name',
        ),
    ]
