# Generated by Django 3.0.3 on 2020-04-29 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0020_remove_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='name',
        ),
    ]
